
<html>
<head>
   <meta http-equiv="content-Type" content="text/html; charset=windows-1251">
   <title>edit-zap n1</title>
</HEAD>
<BODY>
<!--#INCLUDE FILE="save.inc"-->
<%
' записывает корректировки в базу
' Довлетбаев З.С.
' 2019.01.30

OPEN_BAZA("N1")

if NOT Rs.EOF then
   Response.Write "<Table border=1>"
   Response.Write "<TR><TD>поле<TD>в базе<TD>новое значение<TD>запрос"
   Call Write_Rek("орган",    "O")  
   Call Write_Rek("год",      "G")  
   Call Write_Rek("УД",       "N")  
   Call Write_Rek("пор №",     	 "PNK")
   Call Write_Rek("район",       "01")
   Call Write_Rek("год",         "GK")
   Call Write_Rek("№ КУП",     	 "061")
   Call Write_Rek("дата рег.", 	 "062")
   Call Write_MP ("Заявитель", 	 "FAM", "2")
   Call Write_Rek("вид происш",  "HP")
   Call Write_Rek("день нед",  	 "DN")
   Call Write_MP ("Место",     	 "HM",  "3")
   Call Write_Rek("район",     	 "A3")
   Call Write_Rek("нас.пункт", 	 "A4")
   Call Write_Rek("улица",     	 "A5")
   Call Write_Rek("дом",      	 "A6")
   Call Write_Rek("кор",       	 "A7")
   Call Write_Rek("кв",        	 "A8")
   Call Write_Rek("ГОМ",       	 "GOM")
   Call Write_Rek("поручено",  	 "POR")
   Call Write_Rek("получил",   	 "POL")
   Call Write_Rek("дата пол",  	 "DPS")
   Call Write_Rek("решен по КУП","MER")
   Call Write_Rek("дата реш",  	 "DPR")
   Call Write_Rek("вид обв",   	 "03")
' потом надо написать поиск по УД
   Call Write_Rek("УД или отк",   "02")
   Call Write_Rek("№ отказн",     "32")
   Call Write_Rek("пор №",        "04")
   Call Write_Rek("линия работы", "05")
   Call Write_Rek("дата выс 1.0", "07")
   Call Write_Rek("кем предотв",  "08")
   Call Write_Rek("повод к возб", "09")
   Call Write_Rek("неочев",       "10")
   Call Write_Rek("дата соверш",  "11")
   Call Write_Rek("время сут",    "11S")
   Call Write_Rek("кем возб",     "12")
   Call Write_Rek("дата возб",    "13")
   Call Write_Rek("фабула",    	  "FAB") 
   Call Write_Rek("УК",        	  "UK") 
   Call Write_Rek("статья",    	  "15")
   Call Write_MP ("п",         	  "P1", "4")
   Call Write_Rek("статья",    	  "16") 
   Call Write_MP ("п",         	  "P2", "5")
   Call Write_Rek("покушен",      "17")
   Call Write_Rek("доп отметки",  "18")
   Call Write_Rek("тяжесть",      "TJ")
   Call Write_Rek("глава УК",     "GUK")
   Call Write_Rek("город,село",   "19")
   Call Write_Rek("адм участ",    "191")
   Call Write_Rek("общ место",    "20")
   Call Write_Rek("место соверш", "21")
   Call Write_Rek("против собст", "22")
   Call Write_Rek("в сфере экон", "23")
   Call Write_MP ("предметы",     "24", "6")
   Call Write_MP ("ср-ва",    	  "25", "7")
   Call Write_MP ("в отн",        "26", "8")
   Call Write_Rek("иностранца",   "26V")
   Call Write_MP ("проникнов",    "SP", "9")
   Call Write_MP ("нас действ",   "HD", "10")
   Call Write_MP ("под видом",    "PV", "11")
   Call Write_MP ("под предлог",  "PR", "12")
   Call Write_MP ("изьято", 	  "IZ", "13")
   Call Write_Rek("погибло",      "27")
   Call Write_Rek("ранено",       "28")
   Call Write_Rek("следовате",    "29")
   Call Write_Rek("личность",     "RNR")
   Call Write_Rek("дата предьяв", "13D")
   Call Write_Rek("дата загруз ", "ZZZ")
   Call Write_Rek("дата коррек",  "KKK")
   Call Write_Rek("дат выст 1.1", "06P")
   Call Write_MP ("группа", 	  "09P", "14")
   Call Write_Rek("кол сост гру", "10P")
   Call Write_Rek("группа сущ ",  "11L")
   Call Write_Rek("мес      ",    "11M")
   Call Write_MP ("совер лицом",   "12P", "15")
   Call Write_Rek("рез расслед",  "14O")
   Call Write_Rek("дата",      	  "14P")
   Call Write_Rek("кем прекращ",  "16P")
   Call Write_Rek("куда перед",   "05B")
   Call Write_Rek("исх №   ",     "ISX")
   Call Write_Rek("дата",      	  "DIX")
   Call Write_Rek("продлен срок", "06B")
   Call Write_Rek("соед выделен", "07A")
   Call Write_Rek("№ дела   ",    "07B")
   Call Write_Rek("мотив прест",  "17P")
   Call Write_Rek("раскр по гор", "181")
   Call Write_Rek("ущерб    ",    "19P")
   Call Write_Rek("погашено ",    "20P")
   Call Write_Rek("налож арест",  "21P")
   Call Write_Rek("изьято имущ",  "22P")
   Call Write_Rek("изьято к-во ", "231")
   Call Write_Rek("вид 1    ",    "23A")
   Call Write_Rek("изьято к-во ", "232")
   Call Write_Rek("вид 2    ",    "23B")
   Call Write_Rek("изьято оруж ", "241")
   Call Write_Rek("вид 1    ",    "24A")
   Call Write_Rek("изьято оруж ", "242")
   Call Write_Rek("вид 2    ",    "24B")
   Call Write_Rek("изьято нарк ", "251")
   Call Write_Rek("вид 1    ",    "25A")
   Call Write_Rek("изьято нарк ", "252")
   Call Write_Rek("вид 2    ",    "25B")
   Call Write_Rek("изьято нарк ", "253")
   Call Write_Rek("вид 3    ",    "25C")
   Call Write_Rek("вид валюты",   "26S")
   Call Write_Rek("достоинс-м",   "26D")
   Call Write_Rek("кол-во шт  ",  "26K")
   Call Write_Rek("Сл принял ре", "27P")
   Call Write_MP ("№ сообщения ", "28A", "18")
   Call Write_MP ("оп данные вид","28P", "18")
   Call Write_Rek("раскр служба", "29P")
   Call Write_MP ("задержал", 	  "ZAD", "19")
   Call Write_MP ("участие в рас","30P", "19")
   Call Write_MP ("каким орган",  "ROR", "19")
   Call Write_MP ("использование","32P", "16")
   Call Write_Rek("№ РД", 	  "GD")
   Call Write_Rek("-        ",    "RD")
   Call Write_Rek("№ ОПД   ",     "NOP")
   Call Write_Rek("исх в суд",    "39")
   Call Write_Rek("код суда",     "42")
   Call Write_Rek("судья    ",    "42S")
   Call Write_Rek("предмет расс", "43")
   Call Write_Rek("обжалование",  "44")
   Call Write_Rek("решение суда", "48")
   Call Write_Rek("дата пригов",  "49")
   Call Write_Rek("кодекс      ", "50U")
   Call Write_Rek("статья      ", "50")
   Call Write_Rek("пункт       ", "501")
   Call Write_Rek("доп статья  ", "51")
   Call Write_Rek("пункт       ", "511")
   Call Write_Rek("суд апп инст", "45")
   Call Write_Rek("судья ап инс", "45S")
   Call Write_Rek("реш ап инст ", "46")
   Call Write_Rek("осн к отмене", "47")
   Response.Write "</Table>"
   nFmulti=17                                     ' номер файла мульти
   Set rs2 = db.Execute("Select * From ATOC_" & Name_Zad & "_" & nFmulti & " where AT_1=" & ADRES & ";")
   Response.Write "<Table border=1 cellspacing=0 bgcolor=lavender>"  
   nRea=0      
   Do while NOT Rs2.EOF 
      nRea=nRea+1    
      AdresRecM=rs2.Fields("AT_0").value   ' это адрес мультигруппы
      Response.Write "<TR bgColor=LightCyan><TD colspan=4 align=right>" & Adres & "-" & AdresRecM
      Call Write_RekM("пол",         "PL")
      Call Write_RekM("житель",      "JJ") 
      Call Write_RekM("фамилия",     "FA") 
      Call Write_RekM("имя",         "IM") 
      Call Write_RekM("отчество",    "OT") 
      Call Write_RekM("день рожд",   "DR") 
      Call Write_RekM("нац",         "NG") 
      Call Write_RekM("адрес",       "ADR")
      Call Write_RekM("адм.уч",      "ADP")
      Call Write_RekM("дата задерж", "DZD")
      Call Write_RekM("мера прес",   "PRE")
      Call Write_RekM("м.раб",       "ZAN")
      Call Write_RekM("долж",        "DOL")
      Call Write_RekM("род зан",     "RZ") 
      Call Write_RekM("предъ",       "13P")     
      Rs2.MoveNext          
   Loop                    
   Set rs2 = Nothing
   Response.Write "</Table>"  
end if

CLOSE_BAZA

%>
